import Foundation

/// Built-in snippet packs for [Language]. Pure content, no state — the store
/// seeds a copy per pack when the pack is first enabled.
enum LanguagePackSnippets {
    // MARK: Python
    static let python: [TextSnippet] = [
        TextSnippet(trigger: "shebang", expansion: "#!/usr/bin/env python3", description: "Python shebang"),
        TextSnippet(trigger: "main", expansion: "def main():\n    <#body#>\n\n\nif __name__ == \"__main__\":\n    main()", description: "main() with __name__ guard"),
        TextSnippet(trigger: "def", expansion: "def <#name#>(<#args#>):\n    <#body#>", description: "Function"),
        TextSnippet(trigger: "defa", expansion: "async def <#name#>(<#args#>):\n    <#body#>", description: "Async function"),
        TextSnippet(trigger: "defm", expansion: "def <#name#>(self, <#args#>):\n    <#body#>", description: "Method"),
        TextSnippet(trigger: "init", expansion: "def __init__(self, <#args#>):\n    <#body#>", description: "Constructor"),
        TextSnippet(trigger: "class", expansion: "class <#Name#>:\n    def __init__(self, <#args#>):\n        self.<#attr#> = <#value#>\n\n    <#body#>", description: "Class"),
        TextSnippet(trigger: "dataclass", expansion: "@dataclass\nclass <#Name#>:\n    <#field#>: <#type#>", description: "Dataclass"),
        TextSnippet(trigger: "prop", expansion: "@property\ndef <#name#>(self):\n    return self.<#attr#>", description: "Property"),
        TextSnippet(trigger: "statm", expansion: "@staticmethod\ndef <#name#>(<#args#>):\n    <#body#>", description: "Static method"),
        TextSnippet(trigger: "clsm", expansion: "@classmethod\ndef <#name#>(cls, <#args#>):\n    <#body#>", description: "Class method"),
        TextSnippet(trigger: "for", expansion: "for <#item#> in <#iterable#>:\n    <#body#>", description: "For loop"),
        TextSnippet(trigger: "forr", expansion: "for <#i#> in range(<#n#>):\n    <#body#>", description: "For range loop"),
        TextSnippet(trigger: "fore", expansion: "for <#i#>, <#item#> in enumerate(<#iterable#>):\n    <#body#>", description: "For enumerate loop"),
        TextSnippet(trigger: "while", expansion: "while <#condition#>:\n    <#body#>", description: "While loop"),
        TextSnippet(trigger: "if", expansion: "if <#condition#>:\n    <#body#>", description: "If"),
        TextSnippet(trigger: "ife", expansion: "if <#condition#>:\n    <#body#>\nelse:\n    <#else body#>", description: "If / else"),
        TextSnippet(trigger: "ternary", expansion: "<#value#> if <#condition#> else <#fallback#>", description: "Conditional expression"),
        TextSnippet(trigger: "tryex", expansion: "try:\n    <#body#>\nexcept <#Exception#> as e:\n    <#handler#>", description: "Try / except"),
        TextSnippet(trigger: "tryfin", expansion: "try:\n    <#body#>\nfinally:\n    <#cleanup#>", description: "Try / finally"),
        TextSnippet(trigger: "withopen", expansion: "with open(<#path#>, \"<#r#>\") as f:\n    <#body#>", description: "Open file with context manager"),
        TextSnippet(trigger: "lambda", expansion: "<#name#> = lambda <#args#>: <#expr#>", description: "Lambda"),
        TextSnippet(trigger: "listcomp", expansion: "[<#expr#> for <#x#> in <#iterable#>]", description: "List comprehension"),
        TextSnippet(trigger: "dictcomp", expansion: "{<#key#>: <#value#> for <#key#>, <#value#> in <#items#>}", description: "Dict comprehension"),
        TextSnippet(trigger: "fstr", expansion: "f\"<#name#>={<#value#>}\"", description: "f-string"),
        TextSnippet(trigger: "print", expansion: "print(<#value#>)", description: "Print"),
        TextSnippet(trigger: "printd", expansion: "print(f\"{<#var#>=}\")", description: "Debug print variable"),
        TextSnippet(trigger: "assert", expansion: "assert <#condition#>, \"<#message#>\"", description: "Assert"),
        TextSnippet(trigger: "match", expansion: "match <#value#>:\n    case <#pattern#>:\n        <#body#>\n    case _:\n        <#fallback#>", description: "match statement (3.10+)"),
        TextSnippet(trigger: "np", expansion: "import numpy as np", description: "Import NumPy"),
        TextSnippet(trigger: "pd", expansion: "import pandas as pd", description: "Import pandas"),
        TextSnippet(trigger: "plt", expansion: "import matplotlib.pyplot as plt", description: "Import matplotlib"),
    ]

    // MARK: JavaScript
    static let javascript: [TextSnippet] = [
        TextSnippet(trigger: "fn", expansion: "function <#name#>(<#params#>) {\n    <#body#>\n}", description: "Function"),
        TextSnippet(trigger: "afn", expansion: "const <#name#> = async (<#params#>) => {\n    <#body#>\n};", description: "Async arrow function"),
        TextSnippet(trigger: "arrow", expansion: "const <#name#> = (<#params#>) => <#expr#>;", description: "Arrow function"),
        TextSnippet(trigger: "iife", expansion: "(function () {\n    <#body#>\n})();", description: "Immediately invoked function"),
        TextSnippet(trigger: "class", expansion: "class <#Name#> {\n    constructor(<#params#>) {\n        <#body#>\n    }\n}", description: "Class"),
        TextSnippet(trigger: "clog", expansion: "console.log(<#value#>);", description: "console.log"),
        TextSnippet(trigger: "cerr", expansion: "console.error(<#value#>);", description: "console.error"),
        TextSnippet(trigger: "for", expansion: "for (let <#i#> = 0; <#i#> < <#n#>; <#i#>++) {\n    <#body#>\n}", description: "For loop"),
        TextSnippet(trigger: "forof", expansion: "for (const <#item#> of <#items#>) {\n    <#body#>\n}", description: "For-of loop"),
        TextSnippet(trigger: "forin", expansion: "for (const <#key#> in <#obj#>) {\n    <#body#>\n}", description: "For-in loop"),
        TextSnippet(trigger: "foreach", expansion: "<#items#>.forEach((<#item#>) => {\n    <#body#>\n});", description: "forEach"),
        TextSnippet(trigger: "while", expansion: "while (<#condition#>) {\n    <#body#>\n}", description: "While loop"),
        TextSnippet(trigger: "ternary", expansion: "<#condition#> ? <#then#> : <#else#>;", description: "Ternary"),
        TextSnippet(trigger: "try", expansion: "try {\n    <#body#>\n} catch (error) {\n    <#handler#>\n}", description: "try / catch"),
        TextSnippet(trigger: "tryf", expansion: "try {\n    <#body#>\n} catch (error) {\n    <#handler#>\n} finally {\n    <#cleanup#>\n}", description: "try / catch / finally"),
        TextSnippet(trigger: "prom", expansion: "new Promise((resolve, reject) => {\n    <#body#>\n});", description: "Promise"),
        TextSnippet(trigger: "asyncf", expansion: "async function <#name#>(<#params#>) {\n    <#body#>\n}", description: "Async function"),
        TextSnippet(trigger: "await", expansion: "const <#result#> = await <#promise#>;", description: "Await"),
        TextSnippet(trigger: "fetch", expansion: "const res = await fetch(<#url#>);\nif (!res.ok) throw new Error(`HTTP ${res.status}`);\nconst data = await res.json();", description: "Fetch JSON"),
        TextSnippet(trigger: "map", expansion: "<#items#>.map((<#item#>) => <#expr#>);", description: "Array map"),
        TextSnippet(trigger: "filter", expansion: "<#items#>.filter((<#item#>) => <#condition#>);", description: "Array filter"),
        TextSnippet(trigger: "reduce", expansion: "<#items#>.reduce((acc, <#item#>) => <#expr#>, <#initial#>);", description: "Array reduce"),
        TextSnippet(trigger: "import", expansion: "import <#module#> from \"<#module#>\";", description: "Import module"),
        TextSnippet(trigger: "export", expansion: "export const <#name#> = <#value#>;", description: "Export const"),
        TextSnippet(trigger: "exportdef", expansion: "export default <#name#>;", description: "Export default"),
        TextSnippet(trigger: "require", expansion: "const <#module#> = require(\"<#module#>\");", description: "require (CommonJS)"),
        TextSnippet(trigger: "modulex", expansion: "module.exports = {\n    <#name#>,\n};", description: "module.exports"),
        TextSnippet(trigger: "settimeout", expansion: "setTimeout(() => {\n    <#body#>\n}, <#ms#>);", description: "setTimeout"),
        TextSnippet(trigger: "destr", expansion: "const { <#prop#>, <#prop2#> } = <#obj#>;", description: "Object destructuring"),
        TextSnippet(trigger: "listener", expansion: "document.querySelector(\"<#selector#>\").addEventListener(\"<#click#>\", (event) => {\n    <#body#>\n});", description: "DOM event listener"),
        TextSnippet(trigger: "jsonstr", expansion: "JSON.stringify(<#obj#>, null, 2)", description: "JSON stringify"),
        TextSnippet(trigger: "usestate", expansion: "const [<#state#>, set<#State#>] = useState(<#initial#>);", description: "React useState"),
        TextSnippet(trigger: "useeffect", expansion: "useEffect(() => {\n    <#body#>\n}, [<#deps#>]);", description: "React useEffect"),
        TextSnippet(trigger: "cmp", expansion: "function <#Component#>(<#props#>) {\n    return (\n        <div>\n            <#body#>\n        </div>\n    );\n}\n\nexport default <#Component#>;", description: "React component"),
    ]

    // MARK: Java
    static let java: [TextSnippet] = [
        TextSnippet(trigger: "main", expansion: "public static void main(String[] args) {\n    <#body#>\n}", description: "main method"),
        TextSnippet(trigger: "sout", expansion: "System.out.println(<#message#>);", description: "Print line"),
        TextSnippet(trigger: "serr", expansion: "System.err.println(<#message#>);", description: "Error print line"),
        TextSnippet(trigger: "printf", expansion: "System.out.printf(\"<#format#>%n\", <#args#>);", description: "Formatted print"),
        TextSnippet(trigger: "class", expansion: "public class <#Name#> {\n    <#body#>\n}", description: "Class"),
        TextSnippet(trigger: "interface", expansion: "public interface <#Name#> {\n    <#body#>\n}", description: "Interface"),
        TextSnippet(trigger: "enumj", expansion: "public enum <#Name#> {\n    <#CONSTANT#>\n}", description: "Enum"),
        TextSnippet(trigger: "record", expansion: "public record <#Name#>(<#Type#> <#field#>) { }", description: "Record"),
        TextSnippet(trigger: "meth", expansion: "public <#void#> <#name#>(<#params#>) {\n    <#body#>\n}", description: "Method"),
        TextSnippet(trigger: "ctor", expansion: "public <#Name#>(<#params#>) {\n    <#body#>\n}", description: "Constructor"),
        TextSnippet(trigger: "getter", expansion: "public <#Type#> get<#Name#>() {\n    return <#field#>;\n}", description: "Getter"),
        TextSnippet(trigger: "setter", expansion: "public void set<#Name#>(<#Type#> <#value#>) {\n    this.<#field#> = <#value#>;\n}", description: "Setter"),
        TextSnippet(trigger: "override", expansion: "@Override\npublic <#void#> <#name#>(<#params#>) {\n    <#body#>\n}", description: "@Override method"),
        TextSnippet(trigger: "importj", expansion: "import <#java.util#>.<#List#>;", description: "Import"),
        TextSnippet(trigger: "pkg", expansion: "package <#com.example#>;", description: "Package declaration"),
        TextSnippet(trigger: "if", expansion: "if (<#condition#>) {\n    <#body#>\n}", description: "If"),
        TextSnippet(trigger: "ternary", expansion: "<#condition#> ? <#then#> : <#else#>", description: "Ternary"),
        TextSnippet(trigger: "forj", expansion: "for (int <#i#> = 0; <#i#> < <#n#>; <#i#>++) {\n    <#body#>\n}", description: "For loop"),
        TextSnippet(trigger: "forej", expansion: "for (var <#item#> : <#items#>) {\n    <#body#>\n}", description: "For-each loop"),
        TextSnippet(trigger: "whilej", expansion: "while (<#condition#>) {\n    <#body#>\n}", description: "While loop"),
        TextSnippet(trigger: "switchj", expansion: "switch (<#value#>) {\n    case <#x#> -> <#body#>;\n    default -> <#fallback#>;\n}", description: "Switch expression"),
        TextSnippet(trigger: "tryj", expansion: "try {\n    <#body#>\n} catch (<#Exception#> e) {\n    <#handler#>\n}", description: "try / catch"),
        TextSnippet(trigger: "tryr", expansion: "try (var <#resource#> = <#new ...#>()) {\n    <#body#>\n}", description: "Try-with-resources"),
        TextSnippet(trigger: "throwj", expansion: "throw new <#IllegalStateException#>(\"<#message#>\");", description: "Throw exception"),
        TextSnippet(trigger: "lambda", expansion: "(<#a#>, <#b#>) -> <#expr#>", description: "Lambda"),
        TextSnippet(trigger: "stream", expansion: "var <#result#> = <#list#>.stream()\n    .filter(<#x#> -> <#condition#>)\n    .map(<#x#> -> <#expr#>)\n    .toList();", description: "Stream pipeline"),
        TextSnippet(trigger: "listj", expansion: "List<<#String#>> <#list#> = new ArrayList<>();", description: "ArrayList"),
        TextSnippet(trigger: "mapj", expansion: "Map<<#String#>, <#Integer#>> <#map#> = new HashMap<>();", description: "HashMap"),
        TextSnippet(trigger: "opt", expansion: "Optional<<#String#>> <#opt#> = Optional.ofNullable(<#value#>);", description: "Optional"),
        TextSnippet(trigger: "thread", expansion: "Thread <#t#> = new Thread(() -> {\n    <#body#>\n});\n<#t#>.start();", description: "Thread"),
        TextSnippet(trigger: "junit", expansion: "@Test\nvoid <#doesSomething#>() {\n    <#body#>\n}", description: "JUnit test"),
        TextSnippet(trigger: "javadoc", expansion: "/**\n * <#Description#>\n *\n * @param <#name#> <#description#>\n * @return <#description#>\n */", description: "Javadoc comment"),
    ]

    // MARK: C#
    static let csharp: [TextSnippet] = [
        TextSnippet(trigger: "cw", expansion: "Console.WriteLine(\"<#text#>\");", description: "Console.WriteLine"),
        TextSnippet(trigger: "cwr", expansion: "var <#input#> = Console.ReadLine();", description: "Console.ReadLine"),
        TextSnippet(trigger: "main", expansion: "static void Main(string[] args)\n{\n    <#body#>\n}", description: "Main method"),
        TextSnippet(trigger: "class", expansion: "public class <#Name#>\n{\n    <#body#>\n}", description: "Class"),
        TextSnippet(trigger: "interface", expansion: "public interface I<#Name#>\n{\n    <#body#>\n}", description: "Interface"),
        TextSnippet(trigger: "enumc", expansion: "public enum <#Name#>\n{\n    <#Value#>\n}", description: "Enum"),
        TextSnippet(trigger: "ns", expansion: "namespace <#MyApp#>;\n\n<#body#>", description: "Namespace"),
        TextSnippet(trigger: "usingc", expansion: "using <#System#>.<#Collections#>;", description: "using directive"),
        TextSnippet(trigger: "prop", expansion: "public <#Type#> <#Name#> { get; set; }", description: "Auto-property"),
        TextSnippet(trigger: "propg", expansion: "public <#Type#> <#Name#> { get; private set; }", description: "Read-only property"),
        TextSnippet(trigger: "ctor", expansion: "public <#Name#>(<#params#>)\n{\n    <#body#>\n}", description: "Constructor"),
        TextSnippet(trigger: "meth", expansion: "public <#void#> <#Name#>(<#params#>)\n{\n    <#body#>\n}", description: "Method"),
        TextSnippet(trigger: "varc", expansion: "var <#name#> = <#value#>;", description: "var declaration"),
        TextSnippet(trigger: "interp", expansion: "$\"<#name#>={<#value#>}\"", description: "String interpolation"),
        TextSnippet(trigger: "if", expansion: "if (<#condition#>)\n{\n    <#body#>\n}", description: "If"),
        TextSnippet(trigger: "ternary", expansion: "<#condition#> ? <#then#> : <#else#>", description: "Ternary"),
        TextSnippet(trigger: "forc", expansion: "for (int <#i#> = 0; <#i#> < <#n#>; <#i#>++)\n{\n    <#body#>\n}", description: "For loop"),
        TextSnippet(trigger: "forec", expansion: "foreach (var <#item#> in <#items#>)\n{\n    <#body#>\n}", description: "foreach loop"),
        TextSnippet(trigger: "whilec", expansion: "while (<#condition#>)\n{\n    <#body#>\n}", description: "While loop"),
        TextSnippet(trigger: "tryc", expansion: "try\n{\n    <#body#>\n}\ncatch (<#Exception#> ex)\n{\n    <#handler#>\n}", description: "try / catch"),
        TextSnippet(trigger: "tryf", expansion: "try\n{\n    <#body#>\n}\nfinally\n{\n    <#cleanup#>\n}", description: "try / finally"),
        TextSnippet(trigger: "usingst", expansion: "using (var <#resource#> = <#expr#>)\n{\n    <#body#>\n}", description: "using statement"),
        TextSnippet(trigger: "switchc", expansion: "switch (<#value#>)\n{\n    case <#x#>:\n        <#body#>\n        break;\n    default:\n        <#fallback#>\n        break;\n}", description: "switch statement"),
        TextSnippet(trigger: "switchx", expansion: "var <#result#> = <#value#> switch\n{\n    <#x#> => <#then#>,\n    _ => <#fallback#>,\n};", description: "switch expression"),
        TextSnippet(trigger: "linq", expansion: "var <#result#> = <#items#>\n    .Where(<#x#> => <#condition#>)\n    .Select(<#x#> => <#expr#>)\n    .ToList();", description: "LINQ pipeline"),
        TextSnippet(trigger: "lambda", expansion: "(<#x#>) => <#expr#>", description: "Lambda"),
        TextSnippet(trigger: "lista", expansion: "var <#list#> = new List<<#T#>>();", description: "List<T>"),
        TextSnippet(trigger: "dict", expansion: "var <#dict#> = new Dictionary<<#string#>, <#T#>>();", description: "Dictionary"),
        TextSnippet(trigger: "task", expansion: "async Task <#Name#>Async(<#params#>)\n{\n    <#body#>\n}", description: "Async method"),
        TextSnippet(trigger: "awaitc", expansion: "var <#result#> = await <#Task#>;", description: "await"),
        TextSnippet(trigger: "region", expansion: "#region <#Name#>\n<#body#>\n#endregion", description: "#region block"),
        TextSnippet(trigger: "unittest", expansion: "[Fact]\npublic void <#Test#>()\n{\n    <#body#>\n}", description: "xUnit test"),
        TextSnippet(trigger: "excep", expansion: "public class <#Name#>Exception : Exception\n{\n    public <#Name#>Exception(string message) : base(message) { }\n}", description: "Custom exception"),
    ]

    // MARK: C / C++
    static let cpp: [TextSnippet] = [
        TextSnippet(trigger: "inc", expansion: "#include <<#header#>>", description: "System include"),
        TextSnippet(trigger: "inch", expansion: "#include \"<#header#>.h\"", description: "Local include"),
        TextSnippet(trigger: "guard", expansion: "#ifndef <#HEADER_H#>\n#define <#HEADER_H#>\n\n<#body#>\n\n#endif // <#HEADER_H#>", description: "Include guard"),
        TextSnippet(trigger: "mainc", expansion: "#include <stdio.h>\n\nint main(int argc, char *argv[])\n{\n    <#body#>\n    return 0;\n}", description: "C main"),
        TextSnippet(trigger: "printf", expansion: "printf(\"<#format#>\\n\", <#args#>);", description: "printf"),
        TextSnippet(trigger: "scanf", expansion: "scanf(\"<#format#>\", &<#var#>);", description: "scanf"),
        TextSnippet(trigger: "structc", expansion: "typedef struct {\n    <#type#> <#field#>;\n} <#Name#>;", description: "typedef struct"),
        TextSnippet(trigger: "enumc", expansion: "typedef enum {\n    <#VALUE#>\n} <#Name#>;", description: "typedef enum"),
        TextSnippet(trigger: "func", expansion: "<#return type#> <#name#>(<#params#>)\n{\n    <#body#>\n    return <#value#>;\n}", description: "Function"),
        TextSnippet(trigger: "voidf", expansion: "void <#name#>(<#params#>)\n{\n    <#body#>\n}", description: "void function"),
        TextSnippet(trigger: "malloc", expansion: "<#type#> *<#ptr#> = (<#type#> *)malloc(<#n#> * sizeof(<#type#>));\nif (<#ptr#> == NULL) {\n    return <#EXIT_FAILURE#>;\n}", description: "malloc with check"),
        TextSnippet(trigger: "freec", expansion: "free(<#ptr#>);\n<#ptr#> = NULL;", description: "free pointer"),
        TextSnippet(trigger: "memcpy", expansion: "memcpy(<#dest#>, <#src#>, <#n#> * sizeof(<#type#>));", description: "memcpy"),
        TextSnippet(trigger: "forc", expansion: "for (int <#i#> = 0; <#i#> < <#n#>; <#i#>++) {\n    <#body#>\n}", description: "For loop"),
        TextSnippet(trigger: "whilec", expansion: "while (<#condition#>) {\n    <#body#>\n}", description: "While loop"),
        TextSnippet(trigger: "ifc", expansion: "if (<#condition#>) {\n    <#body#>\n}", description: "If"),
        TextSnippet(trigger: "ifec", expansion: "if (<#condition#>) {\n    <#body#>\n} else {\n    <#else body#>\n}", description: "If / else"),
        TextSnippet(trigger: "switchc", expansion: "switch (<#value#>) {\ncase <#x#>:\n    <#body#>\n    break;\ndefault:\n    <#fallback#>\n    break;\n}", description: "switch"),
        TextSnippet(trigger: "assertc", expansion: "assert(<#condition#> && \"<#message#>\");", description: "assert"),
        TextSnippet(trigger: "cppclass", expansion: "class <#Name#> {\npublic:\n    <#Name#>();\n    ~<#Name#>();\n\nprivate:\n    <#members#>\n};", description: "C++ class"),
        TextSnippet(trigger: "cout", expansion: "std::cout << <#value#> << std::endl;", description: "cout"),
        TextSnippet(trigger: "cin", expansion: "std::cin >> <#var#>;", description: "cin"),
        TextSnippet(trigger: "vector", expansion: "std::vector<<#T#>> <#v#>;", description: "std::vector"),
        TextSnippet(trigger: "mapcpp", expansion: "std::map<<#K#>, <#V#>> <#m#>;", description: "std::map"),
        TextSnippet(trigger: "autoptr", expansion: "auto <#p#> = std::make_unique<<#T#>>(<#args#>);", description: "unique_ptr"),
        TextSnippet(trigger: "sharedptr", expansion: "auto <#p#> = std::make_shared<<#T#>>(<#args#>);", description: "shared_ptr"),
        TextSnippet(trigger: "rangefor", expansion: "for (const auto &<#item#> : <#container#>) {\n    <#body#>\n}", description: "Range-based for"),
        TextSnippet(trigger: "autoc", expansion: "auto <#name#> = <#expr#>;", description: "auto variable"),
        TextSnippet(trigger: "template", expansion: "template <typename <#T#>>\n<#T#> <#name#>(<#T#> <#a#>)\n{\n    return <#a#>;\n}", description: "Function template"),
        TextSnippet(trigger: "lambdacpp", expansion: "auto <#f#> = [](<#params#>) {\n    <#body#>\n};", description: "Lambda"),
        TextSnippet(trigger: "trycpp", expansion: "try {\n    <#body#>\n} catch (const std::exception &e) {\n    std::cerr << e.what() << std::endl;\n}", description: "try / catch"),
        TextSnippet(trigger: "cast", expansion: "static_cast<<#T#>>(<#expr#>)", description: "static_cast"),
    ]

    // MARK: TypeScript
    static let typescript: [TextSnippet] = [
        TextSnippet(trigger: "intf", expansion: "interface <#Name#> {\n    <#prop#>: <#type#>;\n}", description: "Interface"),
        TextSnippet(trigger: "typea", expansion: "type <#Name#> = {\n    <#prop#>: <#type#>;\n};", description: "Type alias"),
        TextSnippet(trigger: "enumt", expansion: "enum <#Name#> {\n    <#Member#> = <#value#>,\n}", description: "Enum"),
        TextSnippet(trigger: "fnt", expansion: "function <#name#>(<#param#>: <#type#>): <#ReturnType#> {\n    <#body#>\n}", description: "Typed function"),
        TextSnippet(trigger: "afnt", expansion: "const <#name#> = async (<#param#>: <#type#>): Promise<<#ReturnType#>> => {\n    <#body#>\n};", description: "Async typed function"),
        TextSnippet(trigger: "arrowt", expansion: "const <#name#> = (<#param#>: <#type#>): <#ReturnType#> => <#expr#>;", description: "Typed arrow function"),
        TextSnippet(trigger: "classt", expansion: "class <#Name#> implements <#Interface#> {\n    <#prop#>: <#type#>;\n\n    constructor(<#prop#>: <#type#>) {\n        this.<#prop#> = <#prop#>;\n    }\n}", description: "Class with interface"),
        TextSnippet(trigger: "generic", expansion: "function <#identity#><T>(<#value#>: T): T {\n    return <#value#>;\n}", description: "Generic function"),
        TextSnippet(trigger: "importt", expansion: "import { <#name#> } from \"<#module#>\";", description: "Import"),
        TextSnippet(trigger: "importtype", expansion: "import type { <#Name#> } from \"<#module#>\";", description: "Type-only import"),
        TextSnippet(trigger: "expd", expansion: "export default <#name#>;", description: "Export default"),
        TextSnippet(trigger: "expt", expansion: "export type { <#Name#> };", description: "Export type"),
        TextSnippet(trigger: "clog", expansion: "console.log(<#value#>);", description: "console.log"),
        TextSnippet(trigger: "foroft", expansion: "for (const <#item#> of <#items#>) {\n    <#body#>\n}", description: "For-of loop"),
        TextSnippet(trigger: "mapt", expansion: "<#items#>.map((<#item#>: <#T#>): <#U#> => <#expr#>);", description: "Array map"),
        TextSnippet(trigger: "filtert", expansion: "<#items#>.filter((<#item#>: <#T#>) => <#condition#>);", description: "Array filter"),
        TextSnippet(trigger: "reducet", expansion: "<#items#>.reduce((acc: <#T#>[], <#item#>: <#T#>) => <#expr#>, []);", description: "Array reduce"),
        TextSnippet(trigger: "tryt", expansion: "try {\n    <#body#>\n} catch (error) {\n    <#handler#>\n}", description: "try / catch"),
        TextSnippet(trigger: "promt", expansion: "new Promise<<#T#>>((resolve, reject) => {\n    <#body#>\n});", description: "Typed Promise"),
        TextSnippet(trigger: "asynct", expansion: "async function <#name#>(): Promise<<#T#>> {\n    <#body#>\n}", description: "Async function"),
        TextSnippet(trigger: "awaitt", expansion: "const <#result#> = await <#promise#> as <#T#>;", description: "Await with cast"),
        TextSnippet(trigger: "fetcht", expansion: "const res = await fetch(<#url#>);\nif (!res.ok) throw new Error(`HTTP ${res.status}`);\nconst data = (await res.json()) as <#T#>;", description: "Fetch JSON typed"),
        TextSnippet(trigger: "nonnull", expansion: "<#value#>!", description: "Non-null assertion"),
        TextSnippet(trigger: "ascast", expansion: "<#value#> as <#Type#>", description: "as cast"),
        TextSnippet(trigger: "partial", expansion: "Partial<<#T#>>", description: "Partial<T>"),
        TextSnippet(trigger: "recordt", expansion: "Record<<#string#>, <#T#>>", description: "Record<K, V>"),
        TextSnippet(trigger: "union", expansion: "type <#Name#> = <#A#> | <#B#>;", description: "Union type"),
        TextSnippet(trigger: "guard", expansion: "function is<#Name#>(<#x#>: unknown): <#x#> is <#Name#> {\n    return <#condition#>;\n}", description: "Type guard"),
        TextSnippet(trigger: "destr", expansion: "const { <#prop#>, ...<#rest#> } = <#obj#>;", description: "Destructuring with rest"),
        TextSnippet(trigger: "fc", expansion: "const <#Component#>: FC<<#Props#>> = (<#props#>) => {\n    return <div>{<#children#>}</div>;\n};", description: "React FC component"),
        TextSnippet(trigger: "usestatet", expansion: "const [<#state#>, set<#State#>] = useState<<#T#>>(<#initial#>);", description: "React useState typed"),
        TextSnippet(trigger: "useeffectt", expansion: "useEffect(() => {\n    <#body#>\n}, [<#deps#>]);", description: "React useEffect"),
    ]

    // MARK: SQL
    static let sql: [TextSnippet] = [
        TextSnippet(trigger: "sel", expansion: "SELECT <#columns#>\nFROM <#table#>;", description: "SELECT"),
        TextSnippet(trigger: "selw", expansion: "SELECT <#columns#>\nFROM <#table#>\nWHERE <#condition#>;", description: "SELECT with WHERE"),
        TextSnippet(trigger: "selo", expansion: "SELECT <#columns#>\nFROM <#table#>\nORDER BY <#column#> DESC\nLIMIT <#n#>;", description: "SELECT with ORDER BY / LIMIT"),
        TextSnippet(trigger: "selg", expansion: "SELECT <#column#>, COUNT(*) AS <#total#>\nFROM <#table#>\nGROUP BY <#column#>\nHAVING COUNT(*) > <#n#>;", description: "SELECT with GROUP BY / HAVING"),
        TextSnippet(trigger: "selj", expansion: "SELECT <#columns#>\nFROM <#table#> t1\nINNER JOIN <#table2#> t2 ON t1.<#id#> = t2.<#table_id#>\nWHERE <#condition#>;", description: "INNER JOIN"),
        TextSnippet(trigger: "sellj", expansion: "SELECT <#columns#>\nFROM <#table#> t1\nLEFT JOIN <#table2#> t2 ON t1.<#id#> = t2.<#table_id#>;", description: "LEFT JOIN"),
        TextSnippet(trigger: "distinct", expansion: "SELECT DISTINCT <#column#>\nFROM <#table#>;", description: "SELECT DISTINCT"),
        TextSnippet(trigger: "alias", expansion: "SELECT t.<#column#>\nFROM <#table#> t;", description: "Table alias"),
        TextSnippet(trigger: "count", expansion: "SELECT COUNT(*)\nFROM <#table#>\nWHERE <#condition#>;", description: "COUNT"),
        TextSnippet(trigger: "ins", expansion: "INSERT INTO <#table#> (<#columns#>)\nVALUES (<#values#>);", description: "INSERT"),
        TextSnippet(trigger: "upd", expansion: "UPDATE <#table#>\nSET <#column#> = <#value#>\nWHERE <#condition#>;", description: "UPDATE"),
        TextSnippet(trigger: "del", expansion: "DELETE FROM <#table#>\nWHERE <#condition#>;", description: "DELETE"),
        TextSnippet(trigger: "ct", expansion: "CREATE TABLE <#table#> (\n    id INTEGER PRIMARY KEY,\n    <#column#> <#TYPE#> NOT NULL,\n    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP\n);", description: "CREATE TABLE"),
        TextSnippet(trigger: "at", expansion: "ALTER TABLE <#table#>\nADD COLUMN <#column#> <#TYPE#>;", description: "ALTER TABLE add column"),
        TextSnippet(trigger: "drop", expansion: "DROP TABLE IF EXISTS <#table#>;", description: "DROP TABLE"),
        TextSnippet(trigger: "trunc", expansion: "TRUNCATE TABLE <#table#>;", description: "TRUNCATE TABLE"),
        TextSnippet(trigger: "crview", expansion: "CREATE VIEW <#view_name#> AS\nSELECT <#columns#>\nFROM <#table#>\nWHERE <#condition#>;", description: "CREATE VIEW"),
        TextSnippet(trigger: "crindex", expansion: "CREATE INDEX <#idx_table_column#>\nON <#table#> (<#column#>);", description: "CREATE INDEX"),
        TextSnippet(trigger: "upsert", expansion: "INSERT INTO <#table#> (<#columns#>)\nVALUES (<#values#>)\nON CONFLICT (<#id#>) DO UPDATE SET <#column#> = <#value#>;", description: "Upsert (SQLite / Postgres)"),
        TextSnippet(trigger: "case", expansion: "CASE\n    WHEN <#condition#> THEN <#value#>\n    ELSE <#default#>\nEND", description: "CASE expression"),
        TextSnippet(trigger: "like", expansion: "WHERE <#column#> LIKE '%<#pattern#>%'", description: "LIKE filter"),
        TextSnippet(trigger: "in", expansion: "WHERE <#column#> IN (<#values#>)", description: "IN filter"),
        TextSnippet(trigger: "between", expansion: "WHERE <#column#> BETWEEN <#start#> AND <#end#>", description: "BETWEEN filter"),
        TextSnippet(trigger: "isnull", expansion: "WHERE <#column#> IS NULL", description: "IS NULL filter"),
        TextSnippet(trigger: "subq", expansion: "SELECT <#columns#>\nFROM <#table#>\nWHERE <#id#> IN (\n    SELECT <#id#>\n    FROM <#table2#>\n    WHERE <#condition#>\n);", description: "Subquery"),
        TextSnippet(trigger: "exists", expansion: "WHERE EXISTS (\n    SELECT 1\n    FROM <#table2#>\n    WHERE <#condition#>\n)", description: "EXISTS filter"),
        TextSnippet(trigger: "union", expansion: "SELECT <#columns#> FROM <#table1#>\nUNION\nSELECT <#columns#> FROM <#table2#>;", description: "UNION"),
        TextSnippet(trigger: "cte", expansion: "WITH <#cte_name#> AS (\n    SELECT <#columns#>\n    FROM <#table#>\n    WHERE <#condition#>\n)\nSELECT *\nFROM <#cte_name#>;", description: "CTE"),
        TextSnippet(trigger: "window", expansion: "ROW_NUMBER() OVER (\n    PARTITION BY <#column#>\n    ORDER BY <#column2#> DESC\n)", description: "Window function"),
        TextSnippet(trigger: "trans", expansion: "BEGIN TRANSACTION;\n\n<#body#>\n\nCOMMIT;", description: "Transaction"),
    ]

    // MARK: Go
    static let go: [TextSnippet] = [
        TextSnippet(trigger: "pkg", expansion: "package <#main#>", description: "Package declaration"),
        TextSnippet(trigger: "imp", expansion: "import (\n    \"<#package#>\"\n)", description: "Import block"),
        TextSnippet(trigger: "impf", expansion: "import \"<#package#>\"", description: "Single import"),
        TextSnippet(trigger: "main", expansion: "func main() {\n    <#body#>\n}", description: "main function"),
        TextSnippet(trigger: "fn", expansion: "func <#name#>(<#params#>) error {\n    <#body#>\n    return nil\n}", description: "Function returning error"),
        TextSnippet(trigger: "fnr", expansion: "func <#name#>(<#params#>) <#T#> {\n    <#body#>\n    return <#value#>\n}", description: "Function with return"),
        TextSnippet(trigger: "meth", expansion: "func (<#r#> *<#Receiver#>) <#Name#>(<#params#>) error {\n    <#body#>\n    return nil\n}", description: "Method"),
        TextSnippet(trigger: "err", expansion: "if err != nil {\n    return <#err#>\n}", description: "if err != nil"),
        TextSnippet(trigger: "errf", expansion: "if err != nil {\n    log.Fatalf(\"<#failed...#>: %v\", err)\n}", description: "if err != nil (fatal)"),
        TextSnippet(trigger: "structg", expansion: "type <#Name#> struct {\n    <#Field#> <#Type#>\n}", description: "Struct"),
        TextSnippet(trigger: "iface", expansion: "type <#Name#> interface {\n    <#Method#>(<#params#>) error\n}", description: "Interface"),
        TextSnippet(trigger: "mapg", expansion: "<#name#> := make(map[<#string#>]<#T#>)", description: "Map"),
        TextSnippet(trigger: "sliceg", expansion: "<#name#> := make([]<#T#>, 0, <#cap#>)", description: "Slice"),
        TextSnippet(trigger: "appendg", expansion: "<#slice#> = append(<#slice#>, <#value#>)", description: "Append to slice"),
        TextSnippet(trigger: "forg", expansion: "for <#i#> := 0; <#i#> < <#n#>; <#i#>++ {\n    <#body#>\n}", description: "For loop"),
        TextSnippet(trigger: "forr", expansion: "for <#i#>, <#v#> := range <#items#> {\n    <#body#>\n}", description: "For range (index + value)"),
        TextSnippet(trigger: "forrange", expansion: "for _, <#v#> := range <#items#> {\n    <#body#>\n}", description: "For range (value only)"),
        TextSnippet(trigger: "ifg", expansion: "if <#condition#> {\n    <#body#>\n}", description: "If"),
        TextSnippet(trigger: "switchg", expansion: "switch <#value#> {\ncase <#x#>:\n    <#body#>\ndefault:\n    <#fallback#>\n}", description: "Switch"),
        TextSnippet(trigger: "selg", expansion: "select {\ncase <#msg#> := <-<#ch#>:\n    <#body#>\ndefault:\n    <#fallback#>\n}", description: "Select"),
        TextSnippet(trigger: "gor", expansion: "go func() {\n    <#body#>\n}()", description: "Goroutine"),
        TextSnippet(trigger: "defer", expansion: "defer <#cleanup#>()", description: "Defer"),
        TextSnippet(trigger: "panicg", expansion: "panic(\"<#message#>\")", description: "Panic"),
        TextSnippet(trigger: "recg", expansion: "defer func() {\n    if r := recover(); r != nil {\n        <#handler#>\n    }\n}()", description: "Recover"),
        TextSnippet(trigger: "chang", expansion: "<#ch#> := make(chan <#T#>, <#buf#>)", description: "Channel"),
        TextSnippet(trigger: "wgg", expansion: "var wg sync.WaitGroup\nfor _, <#item#> := range <#items#> {\n    wg.Add(1)\n    go func(<#item#> <#T#>) {\n        defer wg.Done()\n        <#body#>\n    }(<#item#>)\n}\nwg.Wait()", description: "WaitGroup worker pool"),
        TextSnippet(trigger: "mutex", expansion: "var mu sync.Mutex\n\nmu.Lock()\ndefer mu.Unlock()\n<#body#>", description: "Mutex"),
        TextSnippet(trigger: "ctx", expansion: "ctx, cancel := context.WithTimeout(context.Background(), <#5#>*time.Second)\ndefer cancel()", description: "Context with timeout"),
        TextSnippet(trigger: "httph", expansion: "func <#handler#>(w http.ResponseWriter, r *http.Request) {\n    <#body#>\n}", description: "HTTP handler"),
        TextSnippet(trigger: "hget", expansion: "res, err := http.Get(<#url#>)\nif err != nil {\n    return <#err#>\n}\ndefer res.Body.Close()", description: "HTTP GET"),
        TextSnippet(trigger: "jsong", expansion: "data, err := json.Marshal(<#value#>)\nif err != nil {\n    return <#err#>\n}", description: "json.Marshal"),
        TextSnippet(trigger: "fmtg", expansion: "fmt.Printf(\"<#value#>: %v\\n\", <#value#>)", description: "fmt.Printf"),
        TextSnippet(trigger: "testg", expansion: "func Test<#Name#>(t *testing.T) {\n    <#body#>\n}", description: "Test function"),
        TextSnippet(trigger: "shortv", expansion: "<#name#> := <#value#>", description: "Short variable declaration"),
    ]

    // MARK: Rust
    static let rust: [TextSnippet] = [
        TextSnippet(trigger: "fn", expansion: "fn <#name#>(<#params#>) {\n    <#body#>\n}", description: "Function"),
        TextSnippet(trigger: "fnr", expansion: "fn <#name#>(<#params#>) -> <#T#> {\n    <#body#>\n}", description: "Function with return"),
        TextSnippet(trigger: "mainf", expansion: "fn main() {\n    <#body#>\n}", description: "main function"),
        TextSnippet(trigger: "pubf", expansion: "pub fn <#name#>(<#params#>) -> <#T#> {\n    <#body#>\n}", description: "Public function"),
        TextSnippet(trigger: "let", expansion: "let <#name#> = <#value#>;", description: "let binding"),
        TextSnippet(trigger: "letm", expansion: "let mut <#name#> = <#value#>;", description: "Mutable let binding"),
        TextSnippet(trigger: "structr", expansion: "struct <#Name#> {\n    <#field#>: <#T#>,\n}", description: "Struct"),
        TextSnippet(trigger: "enumr", expansion: "enum <#Name#> {\n    <#Variant#>,\n}", description: "Enum"),
        TextSnippet(trigger: "impl", expansion: "impl <#Name#> {\n    <#body#>\n}", description: "impl block"),
        TextSnippet(trigger: "implt", expansion: "impl <#Trait#> for <#Name#> {\n    <#body#>\n}", description: "Implement trait"),
        TextSnippet(trigger: "trait", expansion: "trait <#Name#> {\n    fn <#method#>(&self) -> <#T#>;\n}", description: "Trait"),
        TextSnippet(trigger: "matchr", expansion: "match <#value#> {\n    <#pattern#> => <#expr#>,\n    _ => <#fallback#>,\n}", description: "match"),
        TextSnippet(trigger: "ifl", expansion: "if let <#Some(x)#> = <#value#> {\n    <#body#>\n}", description: "if let"),
        TextSnippet(trigger: "whilel", expansion: "while let <#Some(x)#> = <#value#> {\n    <#body#>\n}", description: "while let"),
        TextSnippet(trigger: "forr", expansion: "for <#i#> in 0..<#n#> {\n    <#body#>\n}", description: "For range"),
        TextSnippet(trigger: "fore", expansion: "for <#item#> in &<#items#> {\n    <#body#>\n}", description: "For each by reference"),
        TextSnippet(trigger: "opt", expansion: "Option<<#T#>>", description: "Option type"),
        TextSnippet(trigger: "res", expansion: "Result<<#T#>, <#E#>>", description: "Result type"),
        TextSnippet(trigger: "qmark", expansion: "<#expr#>?", description: "? propagate error"),
        TextSnippet(trigger: "unwrap", expansion: "<#value#>.expect(\"<#message#>\")", description: "expect"),
        TextSnippet(trigger: "printl", expansion: "println!(\"<#text#>\");", description: "println!"),
        TextSnippet(trigger: "printfmt", expansion: "println!(\"<#name#> = {:?}\", <#value#>);", description: "Debug println"),
        TextSnippet(trigger: "eprint", expansion: "eprintln!(\"<#message#>: {:?}\", <#err#>);", description: "eprintln!"),
        TextSnippet(trigger: "vec", expansion: "let <#v#>: Vec<<#T#>> = Vec::new();", description: "Vec"),
        TextSnippet(trigger: "format", expansion: "format!(\"<#pattern#>\", <#args#>)", description: "format!"),
        TextSnippet(trigger: "usemod", expansion: "use std::<#collections::HashMap#>;", description: "use declaration"),
        TextSnippet(trigger: "modr", expansion: "mod <#name#> {\n    <#body#>\n}", description: "Module"),
        TextSnippet(trigger: "asf", expansion: "async fn <#name#>(<#params#>) -> Result<<#T#>, Box<dyn Error>> {\n    <#body#>\n}", description: "Async function"),
        TextSnippet(trigger: "threadr", expansion: "let handle = std::thread::spawn(move || {\n    <#body#>\n});\nhandle.join().unwrap();", description: "Thread"),
        TextSnippet(trigger: "arcm", expansion: "Arc<Mutex<<#T#>>>", description: "Arc<Mutex<T>>"),
        TextSnippet(trigger: "derive", expansion: "#[derive(Debug, Clone)]", description: "#[derive]"),
        TextSnippet(trigger: "testr", expansion: "#[test]\nfn <#name#>() {\n    <#body#>\n}", description: "Unit test"),
        TextSnippet(trigger: "doc", expansion: "/// <#Description#>", description: "Doc comment"),
        TextSnippet(trigger: "closure", expansion: "let <#f#> = |<#x#>| <#expr#>;", description: "Closure"),
        TextSnippet(trigger: "boxr", expansion: "Box::new(<#value#>)", description: "Box::new"),
    ]

    // MARK: Kotlin
    static let kotlin: [TextSnippet] = [
        TextSnippet(trigger: "fun", expansion: "fun <#name#>(<#params#>): <#Unit#> {\n    <#body#>\n}", description: "Function"),
        TextSnippet(trigger: "funx", expansion: "fun <#name#>(<#params#>): <#T#> = <#expr#>", description: "Expression body function"),
        TextSnippet(trigger: "maink", expansion: "fun main() {\n    <#body#>\n}", description: "main function"),
        TextSnippet(trigger: "mainargs", expansion: "fun main(args: Array<String>) {\n    <#body#>\n}", description: "main with args"),
        TextSnippet(trigger: "valk", expansion: "val <#name#>: <#Type#> = <#value#>", description: "val declaration"),
        TextSnippet(trigger: "vark", expansion: "var <#name#>: <#Type#> = <#value#>", description: "var declaration"),
        TextSnippet(trigger: "classk", expansion: "class <#Name#>(<#params#>) {\n    <#body#>\n}", description: "Class"),
        TextSnippet(trigger: "dataclsk", expansion: "data class <#Name#>(\n    val <#field#>: <#Type#>,\n)", description: "Data class"),
        TextSnippet(trigger: "objk", expansion: "object <#Name#> {\n    <#body#>\n}", description: "Object"),
        TextSnippet(trigger: "compobj", expansion: "companion object {\n    <#body#>\n}", description: "Companion object"),
        TextSnippet(trigger: "intfk", expansion: "interface <#Name#> {\n    fun <#method#>(): <#T#>\n}", description: "Interface"),
        TextSnippet(trigger: "enumk", expansion: "enum class <#Name#> {\n    <#VALUE#>\n}", description: "Enum class"),
        TextSnippet(trigger: "sealk", expansion: "sealed class <#Name#>", description: "Sealed class"),
        TextSnippet(trigger: "extf", expansion: "fun <#Type#>.<#name#>(<#params#>): <#T#> {\n    <#body#>\n}", description: "Extension function"),
        TextSnippet(trigger: "whenk", expansion: "when (<#value#>) {\n    <#cond#> -> <#body#>\n    else -> <#fallback#>\n}", description: "when expression"),
        TextSnippet(trigger: "fork", expansion: "for (<#i#> in 0 until <#n#>) {\n    <#body#>\n}", description: "For range"),
        TextSnippet(trigger: "forink", expansion: "for (<#item#> in <#items#>) {\n    <#body#>\n}", description: "For-in loop"),
        TextSnippet(trigger: "whilek", expansion: "while (<#condition#>) {\n    <#body#>\n}", description: "While loop"),
        TextSnippet(trigger: "ifex", expansion: "val <#name#> = if (<#condition#>) <#then#> else <#else#>", description: "If expression"),
        TextSnippet(trigger: "tryk", expansion: "try {\n    <#body#>\n} catch (e: <#Exception#>) {\n    <#handler#>\n}", description: "try / catch"),
        TextSnippet(trigger: "nullc", expansion: "<#value#> ?: <#default#>", description: "Elvis operator"),
        TextSnippet(trigger: "letk", expansion: "<#obj#>?.let { <#it#> -> <#body#> }", description: "let with null check"),
        TextSnippet(trigger: "applyk", expansion: "<#obj#>().apply {\n    <#body#>\n}", description: "apply block"),
        TextSnippet(trigger: "lateinit", expansion: "lateinit var <#name#>: <#Type#>", description: "lateinit"),
        TextSnippet(trigger: "lazyk", expansion: "val <#name#>: <#T#> by lazy {\n    <#value#>\n}", description: "Lazy val"),
        TextSnippet(trigger: "listk", expansion: "val <#items#> = listOf(<#item#>)", description: "listOf"),
        TextSnippet(trigger: "mutlist", expansion: "val <#items#> = mutableListOf<<#T#>>()", description: "mutableListOf"),
        TextSnippet(trigger: "mapk", expansion: "val <#map#> = mapOf(<#key#> to <#value#>)", description: "mapOf"),
        TextSnippet(trigger: "lambdak", expansion: "val <#f#>: (<#T#>) -> <#R#> = { <#x#> -> <#body#> }", description: "Lambda"),
        TextSnippet(trigger: "suspendk", expansion: "suspend fun <#name#>(<#params#>): <#T#> {\n    <#body#>\n}", description: "Suspend function"),
        TextSnippet(trigger: "launchk", expansion: "scope.launch {\n    <#body#>\n}", description: "Coroutine launch"),
        TextSnippet(trigger: "printk", expansion: "println(<#value#>)", description: "println"),
        TextSnippet(trigger: "testk", expansion: "@Test\nfun `<#does something#>`() {\n    <#body#>\n}", description: "JUnit 5 test"),
    ]
}
